export const USER_SIGN_UP_LOADING = "USER_SIGN_UP_LOADING";
export const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";

export const USER_SIGN_IN_FAIL = "USER_SIGN_IN_FAIL";
export const USER_SIGN_IN_LOADING = "USER_SIGN_IN_LOADING";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

export const FETCH_CURRENT_USER_LOADING = "FETCH_CURRENT_USER_LOADING";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_ERR = "FETCH_CURRENT_USER_ERR";

export const AUTH_REDUX_RESET = "AUTH_REDUX_RESET";
