export const USER_SIGN_UP_LOADING = "USER_SIGN_UP_LOADING";
export const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";

export const USER_SIGN_IN_FAIL = "USER_SIGN_IN_FAIL";
export const USER_SIGN_IN_LOADING = "USER_SIGN_IN_LOADING";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
