export const GET_QUESTIONS_LOADING = "GET_QUESTIONS_LOADING";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";
export const GET_ALL_AVAILABLE_TAGS_LOADING = "GET_ALL_AVAILABLE_TAGS_LOADING";
export const GET_ALL_AVAILABLE_TAGS_SUCCESS = "GET_ALL_AVAILABLE_TAGS_SUCCESS";
export const GET_ALL_AVAILABLE_TAGS_FAIL = "GET_ALL_AVAILABLE_TAGS_FAIL";
export const CORE_REDUX_RESET = "CORE_REDUX_RESET";

export const CREATE_QUESTION_LOADING = "CREATE_QUESTION_LOADING";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";

export const GET_QUESTION_DETAILS_LOADING = "GET_QUESTION_DETAILS_LOADING";
export const GET_QUESTION_DETAILS_FAIL = "GET_QUESTION_DETAILS_FAIL";
export const GET_QUESTION_DETAILS_SUCCESS = "GET_QUESTION_DETAILS_SUCCESS";

export const ADD_ANSWER_TO_QUESTION_LOADING = "ADD_ANSWER_TO_QUESTION_LOADING";
export const ADD_ANSWER_TO_QUESTION_ERROR = "ADD_ANSWER_TO_QUESTION_ERROR";
export const ADD_ANSWER_TO_QUESTION_SUCCESS = "ADD_ANSWER_TO_QUESTION_SUCCESS";

export const ACCEPT_ANSWER_FAIL = "ACCEPT_ANSWER_FAIL";
export const ACCEPT_ANSWER_LOADING = "ACCEPT_ANSWER_LOADING";
export const ACCEPT_ANSWER_SUCCESS = "ACCEPT_ANSWER_SUCCESS";
